// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh4faph7L9PxZT9OIisbhFFslSfrW5Sv0',
    appId: '1:1038667862120:web:956e504fa577f7248c2bdd',
    messagingSenderId: '1038667862120',
    projectId: 'raillive-ce547',
    authDomain: 'raillive-ce547.firebaseapp.com',
    storageBucket: 'raillive-ce547.firebasestorage.app',
    measurementId: 'G-K76TF9VM4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDYzA3EF8BBtS3I_B4XvAZ-er-KOvec4M',
    appId: '1:1038667862120:android:5276d9873b314a998c2bdd',
    messagingSenderId: '1038667862120',
    projectId: 'raillive-ce547',
    storageBucket: 'raillive-ce547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALvSmuvTMGt-hSYRUoEndToiP5whQVRxQ',
    appId: '1:1038667862120:ios:d282c2bb86d70bd28c2bdd',
    messagingSenderId: '1038667862120',
    projectId: 'raillive-ce547',
    storageBucket: 'raillive-ce547.firebasestorage.app',
    iosBundleId: 'com.example.railLive',
  );
}
