/// Sample restaurant data keyed by station_code.
/// In production, replace this with a remote API or local DB.
const Map<String, dynamic> kRestaurantDataByStation = {
  'KHED': {
    'station_name': 'Khed Railway Station',
    'restaurants': [
      {
        'id': 1,
        'name': 'Hotel Shree Datta',
        'distance_km': 0.3,
        'rating': 4.4,
        'price_range': '₹150-₹350',
        'contact': '+91 9876543210',
        'opening_hours': '7:00 AM - 11:00 PM',
        'menu': [
          {'item': 'Misal Pav', 'price': 80},
          {'item': 'Veg Thali', 'price': 180},
          {'item': 'Tea', 'price': 15},
        ],
      },
      {
        'id': 2,
        'name': 'Konkan Spice Restaurant',
        'distance_km': 0.5,
        'rating': 4.5,
        'price_range': '₹200-₹500',
        'contact': '+91 9876543211',
        'opening_hours': '8:00 AM - 10:30 PM',
        'menu': [
          {'item': 'Fish Thali', 'price': 280},
          {'item': 'Chicken Thali', 'price': 320},
          {'item': 'Solkadhi', 'price': 40},
        ],
      },
      {
        'id': 3,
        'name': 'Sai Krupa Family Restaurant',
        'distance_km': 0.8,
        'rating': 4.3,
        'price_range': '₹180-₹400',
        'contact': '+91 9876543212',
        'opening_hours': '8:00 AM - 11:00 PM',
        'menu': [
          {'item': 'Paneer Masala', 'price': 220},
          {'item': 'Butter Naan', 'price': 40},
          {'item': 'Veg Biryani', 'price': 180},
        ],
      },
      {
        'id': 4,
        'name': 'Hotel Abhiruchi',
        'distance_km': 1.1,
        'rating': 4.2,
        'price_range': '₹150-₹300',
        'contact': '+91 9876543213',
        'opening_hours': '7:00 AM - 10:00 PM',
        'menu': [
          {'item': 'Poha', 'price': 40},
          {'item': 'Upma', 'price': 50},
          {'item': 'South Indian Combo', 'price': 120},
        ],
      },
      {
        'id': 5,
        'name': 'Konkan Darbar',
        'distance_km': 1.4,
        'rating': 4.6,
        'price_range': '₹250-₹600',
        'contact': '+91 9876543214',
        'opening_hours': '11:00 AM - 11:00 PM',
        'menu': [
          {'item': 'Surmai Fry', 'price': 350},
          {'item': 'Prawns Curry', 'price': 320},
          {'item': 'Fish Thali', 'price': 300},
        ],
      },
      {
        'id': 6,
        'name': 'Shiv Sagar Veg Restaurant',
        'distance_km': 1.7,
        'rating': 4.1,
        'price_range': '₹120-₹250',
        'contact': '+91 9876543215',
        'opening_hours': '8:00 AM - 10:00 PM',
        'menu': [
          {'item': 'Pav Bhaji', 'price': 110},
          {'item': 'Masala Dosa', 'price': 120},
          {'item': 'Veg Fried Rice', 'price': 150},
        ],
      },
      {
        'id': 7,
        'name': 'Hotel Gurukrupa',
        'distance_km': 2.0,
        'rating': 4.0,
        'price_range': '₹100-₹250',
        'contact': '+91 9876543216',
        'opening_hours': '7:00 AM - 10:00 PM',
        'menu': [
          {'item': 'Vada Pav', 'price': 20},
          {'item': 'Misal Pav', 'price': 70},
          {'item': 'Tea', 'price': 15},
        ],
      },
      {
        'id': 8,
        'name': 'Blue Ocean Family Restaurant',
        'distance_km': 2.5,
        'rating': 4.5,
        'price_range': '₹250-₹700',
        'contact': '+91 9876543217',
        'opening_hours': '11:00 AM - 11:30 PM',
        'menu': [
          {'item': 'Crab Masala', 'price': 450},
          {'item': 'Pomfret Fry', 'price': 400},
          {'item': 'Chicken Biryani', 'price': 250},
        ],
      },
      {
        'id': 9,
        'name': 'Maharaja Restaurant',
        'distance_km': 3.1,
        'rating': 4.2,
        'price_range': '₹180-₹450',
        'contact': '+91 9876543218',
        'opening_hours': '10:00 AM - 11:00 PM',
        'menu': [
          {'item': 'Punjabi Thali', 'price': 220},
          {'item': 'Paneer Butter Masala', 'price': 240},
          {'item': 'Jeera Rice', 'price': 120},
        ],
      },
      {
        'id': 10,
        'name': 'Konkan Delight',
        'distance_km': 4.0,
        'rating': 4.4,
        'price_range': '₹200-₹550',
        'contact': '+91 9876543219',
        'opening_hours': '11:00 AM - 10:30 PM',
        'menu': [
          {'item': 'Seafood Thali', 'price': 350},
          {'item': 'Chicken Sukka', 'price': 280},
          {'item': 'Solkadhi', 'price': 50},
        ],
      },
    ],
  },
  'RN': {
    'station_name': 'Ratnagiri Railway Station',
    'restaurants': [
      {
        'id': 101,
        'name': 'Alphonso Garden Restaurant',
        'distance_km': 0.4,
        'rating': 4.5,
        'price_range': '₹200-₹600',
        'contact': '+91 9812345678',
        'opening_hours': '8:00 AM - 11:00 PM',
        'menu': [
          {'item': 'Malvani Fish Curry', 'price': 320},
          {'item': 'Bombil Fry', 'price': 250},
          {'item': 'Ukdiche Modak', 'price': 80},
        ],
      },
      {
        'id': 102,
        'name': 'Harbour View Dhaba',
        'distance_km': 0.9,
        'rating': 4.3,
        'price_range': '₹150-₹400',
        'contact': '+91 9823456789',
        'opening_hours': '7:00 AM - 10:30 PM',
        'menu': [
          {'item': 'Crab Thali', 'price': 380},
          {'item': 'Prawn Koliwada', 'price': 280},
          {'item': 'Solkadhi', 'price': 40},
        ],
      },
    ],
  },
  'PUNE': {
    'station_name': 'Pune Junction Railway Station',
    'restaurants': [
      {
        'id': 201,
        'name': 'Vaishali Restaurant',
        'distance_km': 0.5,
        'rating': 4.7,
        'price_range': '₹150-₹400',
        'contact': '+91 9834567890',
        'opening_hours': '8:00 AM - 11:00 PM',
        'menu': [
          {'item': 'Masala Dosa', 'price': 130},
          {'item': 'Filter Coffee', 'price': 40},
          {'item': 'Idli Sambar', 'price': 90},
        ],
      },
      {
        'id': 202,
        'name': 'Dorabjee & Sons',
        'distance_km': 0.8,
        'rating': 4.4,
        'price_range': '₹200-₹500',
        'contact': '+91 9845678901',
        'opening_hours': '9:00 AM - 10:00 PM',
        'menu': [
          {'item': 'Irani Chai', 'price': 30},
          {'item': 'Bun Maska', 'price': 50},
          {'item': 'Keema Pav', 'price': 150},
        ],
      },
    ],
  },
};